//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_Centre.Models.RentalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class msbarangs
    {
        public int id_barang { get; set; }
        public Nullable<int> id_jenisbarang { get; set; }
        public Nullable<int> id_rental { get; set; }
        public string nama_barang { get; set; }
        public Nullable<int> harga_sewa { get; set; }
        public Nullable<int> stok_barang { get; set; }
        public string deskripsi_barang { get; set; }
        public string link_gambar { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> creaby { get; set; }
        public Nullable<System.DateTime> creadate { get; set; }
        public Nullable<int> modiby { get; set; }
        public Nullable<System.DateTime> modidate { get; set; }
    }
}
