//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_Centre.Models.RentalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mskodepos
    {
        public int id_kodepos { get; set; }
        public string kodepos { get; set; }
        public string kelurahan { get; set; }
        public string kecamatan { get; set; }
        public string kota { get; set; }
        public string provinsi { get; set; }
    }
}
